// Từ điển tên lớp IFC -> tiếng Việt, giúp người dùng hiểu bộ lọc cấu kiện.
const IFC_VI: Record<string, string> = {
  // Kết cấu & kiến trúc
  IFCWALL: 'Tường',
  IFCWALLSTANDARDCASE: 'Tường tiêu chuẩn',
  IFCSLAB: 'Sàn / Bản',
  IFCBEAM: 'Dầm',
  IFCCOLUMN: 'Cột',
  IFCFOOTING: 'Móng',
  IFCPILE: 'Cọc',
  IFCROOF: 'Mái',
  IFCSTAIR: 'Cầu thang',
  IFCSTAIRFLIGHT: 'Vế thang',
  IFCRAMP: 'Đường dốc',
  IFCRAMPFLIGHT: 'Vế dốc',
  IFCRAILING: 'Lan can',
  IFCMEMBER: 'Thanh / Cấu kiện thanh',
  IFCPLATE: 'Tấm',
  IFCCOVERING: 'Lớp phủ / Trần',
  IFCCURTAINWALL: 'Tường kính (mặt dựng)',
  IFCDOOR: 'Cửa đi',
  IFCWINDOW: 'Cửa sổ',
  IFCSPACE: 'Không gian / Phòng',
  IFCSITE: 'Khu đất',
  IFCBUILDING: 'Tòa nhà',
  IFCBUILDINGSTOREY: 'Tầng',
  IFCBUILDINGELEMENTPROXY: 'Cấu kiện chung (proxy)',
  IFCFURNISHINGELEMENT: 'Nội thất',
  IFCFURNITURE: 'Đồ đạc',
  // MEP — Cơ điện
  IFCFLOWSEGMENT: 'Đoạn ống/ống gió',
  IFCFLOWFITTING: 'Phụ kiện nối ống',
  IFCFLOWTERMINAL: 'Thiết bị đầu cuối (vòi/đèn/miệng gió)',
  IFCFLOWCONTROLLER: 'Thiết bị điều khiển dòng (van...)',
  IFCFLOWMOVINGDEVICE: 'Thiết bị tạo dòng (bơm/quạt)',
  IFCFLOWSTORAGEDEVICE: 'Thiết bị chứa (bồn/bể)',
  IFCFLOWTREATMENTDEVICE: 'Thiết bị xử lý',
  IFCDISTRIBUTIONELEMENT: 'Thiết bị phân phối',
  IFCDISTRIBUTIONPORT: 'Cổng kết nối MEP',
  IFCDISTRIBUTIONELEMENTTYPE: 'Loại thiết bị phân phối',
  IFCPIPESEGMENT: 'Đoạn ống',
  IFCPIPEFITTING: 'Phụ kiện ống',
  IFCDUCTSEGMENT: 'Đoạn ống gió',
  IFCDUCTFITTING: 'Phụ kiện ống gió',
  IFCCABLECARRIERSEGMENT: 'Máng/thang cáp',
  IFCCABLESEGMENT: 'Đoạn cáp',
  IFCSANITARYTERMINAL: 'Thiết bị vệ sinh',
  IFCLIGHTFIXTURE: 'Đèn chiếu sáng',
  IFCELECTRICAPPLIANCE: 'Thiết bị điện',
  IFCOUTLET: 'Ổ cắm / Hộp nối',
  IFCSWITCHINGDEVICE: 'Công tắc / Thiết bị đóng cắt',
  IFCVALVE: 'Van',
  IFCPUMP: 'Bơm',
  IFCFAN: 'Quạt',
  IFCAIRTERMINAL: 'Miệng gió',
  IFCSPACEHEATER: 'Thiết bị sưởi',
  // Hệ thống & nhóm
  IFCSYSTEM: 'Hệ thống',
  IFCBUILDINGSYSTEM: 'Hệ thống tòa nhà',
  IFCZONE: 'Vùng',
  IFCGROUP: 'Nhóm',
  // Vật liệu & metadata (phi hình học)
  IFCMATERIAL: 'Vật liệu',
  IFCMATERIALLAYER: 'Lớp vật liệu',
  IFCMATERIALLAYERSET: 'Bộ lớp vật liệu',
  IFCMATERIALLAYERSETUSAGE: 'Áp dụng lớp vật liệu',
  IFCMATERIALDEFINITIONREPRESENTATION: 'Biểu diễn vật liệu',
  IFCPROPERTYSET: 'Bộ thuộc tính',
  IFCELEMENTQUANTITY: 'Khối lượng cấu kiện',
  IFCCLASSIFICATION: 'Phân loại',
  IFCAPPLICATION: 'Ứng dụng (phần mềm)',
  IFCPROJECT: 'Dự án',
  IFCUNITASSIGNMENT: 'Gán đơn vị',
  IFCDERIVEDUNIT: 'Đơn vị dẫn xuất',
  IFCDERIVEDUNITELEMENT: 'Phần tử đơn vị dẫn xuất',
  IFCCONVERSIONBASEDUNIT: 'Đơn vị quy đổi',
  IFCDIMENSIONALEXPONENTS: 'Số mũ thứ nguyên',
  IFCMEASUREWITHUNIT: 'Giá trị có đơn vị',
  IFCELEMENT: 'Cấu kiện',
};

/** Trả về nhãn tiếng Việt cho lớp IFC (rỗng nếu chưa có trong từ điển). */
export function ifcClassLabel(cat: string): string {
  if (!cat) return '';
  return IFC_VI[cat.toUpperCase()] ?? '';
}
